name: Java CI with Maven and S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to latest version
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Cache Maven packages  # Add caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -DskipTests -Djar.finalName=sample-0.0.1-SNAPSHOT 
      - name: Verify Build Artifacts
        run: ls -l target/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 
      - name: Upload to S3
        run: aws s3 cp target/sample-0.0.1-SNAPSHOT.jar s3://applicationspringboot/sample-0.0.1-SNAPSHOT.jar
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20  # Updated to latest version
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: springboots 
          environment_name: Springboots-env 
          version_label: ${{ github.SHA }} 
          region: ap-south-1
          deployment_package: target/sample-0.0.1-SNAPSHOT.jar  # Deploy directly from target